# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='database',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='folder',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
